---
- name: "Assign vCenter Permission for role '{{ vcsa_role }}' to '{{ vcsa_ad_dom_join_domain }}\\{{ vcsa_group }}'"
  vmware_object_role_permission:
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_sso_username }}"
    password: "{{ vcsa_sso_password }}"
    validate_certs: "{{ ova_validate_certs }}"
    role: "{{ vcsa_role }}"
    group: "{{ vcsa_ad_dom_join_domain }}\\{{ vcsa_group }}"
    object_type: "Folder"
    object_name: "rootFolder"
    state: present
  delegate_to: localhost