---
- name: Wait for firstboot operation to complete
  wait_for:
    path: "/var/log/firstboot/firstbootStatus.json"
    search_regex: '"finalStatus": "(failure|success)"'
    sleep: 10
    timeout: 900

- name: Read firstboot.json file
  slurp:
    src: "/var/log/firstboot/firstbootStatus.json"
  register: firstboot_file

- name: Set firstboot.json content
  set_fact:
    firstboot_file_content: "{{ firstboot_file.content | b64decode }}"

- name: Get error message if operation has failed
  shell: "tail /var/log/firstboot/*firstboot*stderr.log -n 20"
  register: vcsa_error_log
  changed_when: false
  when: firstboot_file_content.finalStatus == "failure"

- name: Check if firstboot operation failed
  fail:
    msg: |
      "vCenter Server deployment failed at {{ firstboot_file_content.failedSteps }}"
      "Error was:"

      "{{ vcsa_error_log.stdout }}"
  when: firstboot_file_content.finalStatus == "failure"