galaxy_info:
  author: Gavin Stephens
  description: Deploy and configure the vCenter Server Appliance
  role_name: vmware_deploy_vcsa

  license: MIT

  min_ansible_version: 2.8

  platforms:
  - name: vCenter
    versions:
    - 6.5
    - 6.7
  - name: vSphere
    version:
    - 6.5
    - 6.7

  galaxy_tags:
    - vmware
    - vcenter
    - vcsa
    - vrealize

dependencies:
  - role: vmware_deploy_ova